.github/workflows/compile.yml, lua/dbee/install/init.lua
Doesn't require the CI pipeline to work, and easier to verify that binary matches source code.
~~Not tested on windows, not sure if the path needs to be normalized.~~ Seems to work, at least in Git Bash, and whatever `winget install Neovim.Neovim` installed.
=> Use `go build` instead of `go install`

README.md, doc/dbee-reference.txt, doc/dbee.txt, lua/dbee/api/ui.lua, lua/dbee/config.lua, lua/dbee/ui/result/init.lua
This merge request:
* Enables the user to navigate  to first and last pages of result. I personally find it very useful when I have ordered by a certain column and the last result entry might contain the item I want to explore. 
* Updated the README for the above changes **to show in a table** which I thought might be will improve the accessibility of it.
=> Feat: Navigate to first and last pages of result

lua/dbee/ui/result/init.lua
This merge request:
Shows number of rows returned by the query. I find this feature very useful instead of going manually to the last page or writing a separate query using COUNT(*) to see how many rows does the query returns.
=> Feat: show total number of rows returned by the query

dbee/handler/event_bus.go, dbee/handler/handler.go, lua/dbee/doc.lua
New feature which allows exposure of events if the database has changed.
This is useful for cmp-dbee to request a new "structure" of the database even if the connection stays the same.
I wanted to add this to e.g. "current_connection_change" but since some adapters don't have the concept of "databases" I decided to add a new one to have clean separation.
=> feat: add current_database_changed event bus

lua/dbee/ui/drawer/convert.lua
The`nvim_buf_get_option` is depricated from `nvim-0.10`: https://neovim.io/doc/user/deprecated.html#nvim_buf_get_option()
This simply re-enables the little "dot" that indicates if a buffer is modified, using a backwards compatible check.
=> fix: Add version check for buffer option

lua/dbee/ui/drawer/convert.lua
This is just a small thing, but it kinda annoyed me. 🙃 
The help functions in the left side menu was ordered in different ways every time it was opened so I changed the sorting to sort by name instead of id to get a consistent sorting.
I hope it's okay that I created a PR for this.
=> fix: sort help functions by action name

.github/workflows/compile.yml, .github/workflows/docgen.yml, .github/workflows/lint.yml, .github/workflows/test.yml, ci/target-matrix.sh, ci/targets.json
- the version of `upload-artifact` and `download-artifact` has been deprecated -> update to latest.
- make sure we run CI/CD on `compile` for the 6 "1st class citizen" platform on PR triggers (but allow for full build by `workflow_dispatch`)
- update the trigger on the CI/CD to essentially:
- only runs on meaningful events (PRs and master branch)
- concurrency settings prevent redundant runs
=> ci: fix artifacts workflow and update trigger events

dbee/adapters/clickhouse.go, dbee/adapters/clickhouse_driver.go, dbee/go.mod, dbee/go.sum, dbee/tests/integration/clickhouse_integration_test.go, dbee/tests/testdata/clickhouse_seed.sql, dbee/tests/testhelpers/clickhouse.go, dbee/tests/testhelpers/helper.go
- add basic integration tests structure for `clickhouse` adapter
- add ping check on the connection to make sure it is connected succesfully
- revert switch database if fails etc
- update `GetResult` in testhelpers to fetch result for `CallStateArchived` state
=> test: integration tests for `clickhouse`

.github/workflows/test.yml
Given we are now starting to have a few testcontainer tests, we might want to parallelize them as part of the CI/CD. This is a quick bootstrap to retrieve each adapter file and run it independently.
I realize we have the `./ci` folder, which contains CI/CD scripts. However, I don't think this part need to have it own bash script yet, given it is quite simple/small. I also think it make more sense to "dynamically" detect adapters from the file structure rather than adding the adapter name in the CI/CD part (we want to hide that logic from contributors - they should only care about adding a new 'adapter' test file IMHO).
=> ci(test): add matrix bootstrap for testcontainer parallelization

README.md
The `mysql://` component causes connection errors as it tries to connect with the username `mysql`. Also the `tcp(...)` component is probably what most people will want, so best to have it in the documented example.
=> Update the MySQL connection url to the format supported

dbee/adapters/sqlite.go, dbee/adapters/sqlite_driver.go, dbee/go.mod, dbee/tests/integration/sqlite_integration_test.go, dbee/tests/testdata/sqlite_seed.sql, dbee/tests/testhelpers/sqlite.go
Some changes to the driver to mimic how we do it in other places.
The tests in this case might be a bit bloated/unorthodox, given sqlite is lightweight and containers aren't 'truly' needed.
However, in order to easier reproduce dependencies/seed etc it is useful to have an isolated container, where tools related to specific sqlite-driver can be installed (not up to the developer to have e.g. sqlite3 CLI installed). For example, adding the seed in this case is done via the `sqlite3` CLI, which the CI/CD or developers _might_ have. But, what they do have is docker/virtualisation installed and that is IMO the only tool a developer should need to run the tests. WDYT?
EDIT: I know there is a preinstalled sqlite image (https://hub.docker.com/r/keinos/sqlite3) but I chose simplicity/control by …
=> test: integration tests for `sqlite`

.github/workflows/test.yml, dbee/adapters/bigquery.go
some QoL stuff
- bigquery charges of the underlying tables size, not processed data -> ergo `LIMIT` doesn't apply, change to specific for bigquery
- run containers on PRs/pushes on `master`
=> chore: bigquery refactoring and CI/CD update

lua/dbee/ui/result/init.lua
This is to add more control to the result focus window step. This is needed to mitigate the window title being added for the "Results" winbar.
This is to fix https://github.com/kndndrj/nvim-dbee/pull/167
Before:
After this change:
=> hotfix: Add focus result window function

.github/workflows/test.yml, dbee/adapters/duck.go, dbee/adapters/duck_driver.go, dbee/adapters/duck_driver_test.go, dbee/tests/integration/duckdb_integration_test.go, dbee/tests/testdata/duckdb_seed.sql, dbee/tests/testhelpers/duckdb.go, dbee/tests/testhelpers/sqlite.go
This follows the style and structure of both the postgres and bigquery integration tests.
---
_Edit:_ There seems to be some issue with the adapter. Will investigate it. Resolved by commit `98bac14ceda3`:
```
Add Archived state in GetResult to not run async
This is a fix provided by @MattiasMTS in:
http://github.com/kndndrj/nvim-dbee/pull/177/files#diff-5234895d59f82777fe5b7e9e89ec74f054246a480b63d168a00142551ef6c6bcR48
```
- Resolved by adding more depth to the driver's structure.
- Resolved by adding the current database to show, but not allowing switching
---
```
--- PASS: TestDuckDBTestSuite/TestListOnlyOneDatabase (0.00s)
--- PASS: TestDuckDBTestSuite/TestShouldCancelQuery (0.10s)
--- PASS: TestDuckDBTestSuite/TestShouldFailInvalidQuery (0.00s)
--- PASS: …
```
=> test: integration tests for `duckdb`

dbee/tests/testhelpers/sqlite.go
Relax the version of `sqlite` on `alpine:3.21`. Should probably be locked soon ones alpine is done iterating on this version.
=> fix(tests): relax sqlite version

lua/dbee/ui/editor/init.lua
This fixes https://github.com/kndndrj/nvim-dbee/issues/154.
For some reason, when creating a new note (local or global), the filetype for the new buffer was being set to `sql`, but treesitter wasn't picking up the filetype for syntax highlighting.
This is a bit of a hack, but I found that explicitly setting the filetype to `sql` on the buffer seems to resolve the issue 🤷
=> fix: explicitly set the `sql` filetype on new notes

dbee/tests/testhelpers/sqlite.go, lua/dbee.lua, lua/dbee/layouts/init.lua
~~Adds options to the `require('dbee').open( { reset = true } )`,~~ which will reset the windows to the fixed size defined in layout config.
The reset functionality is now build into the `require('dbee').open()`, such that:
1. If not yet open, it will open
2. If open, it will reset the layout
A question is if we want it to be hard coded, or dynamically calculated relative to the terminal current size. Any thoughts @MattiasMTS?
=> feat(editor): Add reset option to dbee open

lua/dbee/sources.lua, lua/dbee/ui/editor/init.lua
Before this PR, the app would attempt to eagerly load all global and local notes from disk. Unfortunately, there was a bug in the algorithm, such that it would load ONLY global notes (and not local notes).
Rather than fix the bug in the "eager-loading" strategy, I think it would be easier to switch to a "lazy-loading" strategy, i.e. lazily load notes from disk, per-namespace. This also ends up fixing the original bug.
This should resolve https://github.com/kndndrj/nvim-dbee/issues/151.
Tested locally.
=> fix: ensure that local notes are loaded properly from disk

dbee/adapters/clickhouse_driver.go
I have found the use of unstable methods for obtaining a list of tables and information about them, especially in conditions of limited access. 
propose a more optimal and universal solution.
=> fix: edit clickhouse driver query's

lua/dbee/config.lua, lua/dbee/ui/editor/init.lua, lua/dbee/utils.lua
~edit: I'll try to add treesitter into this as per https://github.com/MattiasMTS/cmp-dbee/blob/ms/v2/lua/cmp-dbee/treesitter/init.lua to support when one is running more complex queries, e.g. multiple CTEs.~ 
**EDIT2:** solved, added treesitter to support more complex queries.
Solves #121. As per the discussions in that thread, there are various ways to do this.
We can discuss wether we want this to be ported into the `main` or just be part of discussion somewhere. It definitely improve the UX a bit - similar to Jetbrain's datagrip style.
Video:
**EDIT2:** uploaded new file with more complex queries
https://github.com/user-attachments/assets/e790897a-32f5-49f9-9d61-6edca4e06aca
=> feat(editor): add run_under_cursor
